### ISSUE TITLE
Add Syntax Highlighting In Documentation

### ISSUE THREAD

**Issue by GloverDonovan** [reapp/oldreapp..github.io#10]
I suggest the addition of syntax highlighting in the documentation.

Maybe https://highlightjs.org/ ? Disclaimer: I <3 highlight.js

**Comment by natew** [comment]
Would gladly accept a pull request until we can get to this. The homepage already uses prism, but we don't use line numbers so we could switch.

**Comment by GloverDonovan** [comment]
Marking this as closed since the new design has highlighting
